### ISSUE TITLE
CommandUsed errors in mouse gut taxonomic_profiling.tsv?

### ISSUE THREAD

**Issue by dkoslicki** [CAMI-challenge/data#1]
I'm curious as to why the MetaPalette (row 9 in [this file](https://github.com/CAMI-challenge/data/blob/master/CAMI2/toy/mouse_gut/taxonomic_profiling.tsv)) CommandUsed column calls a Julia program, when MetaPalette is written in Python and doesn't use Julia.

Similarly, FOCUS (row 5) has a CommandUsed that references a script `focus_cami.py` that is not provided in the repo listed in the SoftwareURL column (https://github.com/metageni/FOCUS).

Might be useful to address given that the tutorial manuscript points to this repo.

**Comment by fernandomeyer** [comment]
Such scripts are in the respective docker images to satisfy the requirements of bioboxes. If this causes confusion, I can provide the docker command instead.

**Comment by fernandomeyer** [comment]
Docker commands are now provided for bioboxes. Fixed in 813aee02885f51e827837b5ae911a284fa880ed7
